//! Borrowed Native ABI transport and exports generated by the SDK macro.

use crate::{Host, Plugin, Result, SdkError};
use std::ffi::c_void;
use ting_plugin_contract::format_calls::{ChunkRef, MAX_MEDIA_CHUNK_BYTES, ResourceId};
use ting_plugin_contract::native_abi::*;
use ting_plugin_contract::protocol::PluginErrorCode;

pub const MAX_CONTROL_BYTES: usize = MAX_NATIVE_CONTROL_BYTES;

pub struct NativeHost<'a>(&'a NativeHostApiV2);

pub(crate) fn check_status(status: i32) -> Result<()> {
    if status == 0 {
        return Ok(());
    }
    let code = match status {
        -1 => PluginErrorCode::InvalidInput,
        -2 | -4 => PluginErrorCode::PermissionDenied,
        -3 => PluginErrorCode::NotFound,
        -5 => PluginErrorCode::ResourceLimit,
        -6 => PluginErrorCode::Cancelled,
        -8 => PluginErrorCode::UnsupportedOperation,
        _ => PluginErrorCode::InternalError,
    };
    Err(SdkError::new(code, "Host operation failed"))
}

impl Host for NativeHost<'_> {
    fn invoke(&self, method: &str, input: serde_json::Value) -> Result<serde_json::Value> {
        let input = serde_json::to_vec(&input).map_err(SdkError::parse)?;
        if input.len() > MAX_CONTROL_BYTES || method.len() > 128 {
            return Err(SdkError::invalid("Host control input exceeds limit"));
        }
        let mut output = vec![0u8; MAX_CONTROL_BYTES];
        let mut length = 0;
        check_status(unsafe {
            (self.0.invoke)(
                self.0.user_data,
                method.as_ptr(),
                method.len(),
                input.as_ptr(),
                input.len(),
                output.as_mut_ptr(),
                output.len(),
                &mut length,
            )
        })?;
        serde_json::from_slice(
            output
                .get(..length)
                .ok_or_else(|| SdkError::invalid("Invalid Host result length"))?,
        )
        .map_err(SdkError::parse)
    }

    fn read_at(&self, id: &ResourceId, offset: u64, max_bytes: usize) -> Result<(Vec<u8>, bool)> {
        if max_bytes == 0 || max_bytes > MAX_MEDIA_CHUNK_BYTES as usize {
            return Err(SdkError::invalid("Invalid resource read length"));
        }
        let mut output = vec![0u8; max_bytes];
        let mut length = 0;
        let mut eof = false;
        check_status(unsafe {
            (self.0.read_at)(
                self.0.user_data,
                id.0.as_ptr(),
                id.0.len(),
                offset,
                output.as_mut_ptr(),
                output.len(),
                &mut length,
                &mut eof,
            )
        })?;
        if length > output.len() {
            return Err(SdkError::invalid("Invalid Host read length"));
        }
        output.truncate(length);
        Ok((output, eof))
    }

    fn write_at(&self, id: &ResourceId, offset: u64, bytes: &[u8]) -> Result<usize> {
        let mut written = 0;
        check_status(unsafe {
            (self.0.write_at)(
                self.0.user_data,
                id.0.as_ptr(),
                id.0.len(),
                offset,
                bytes.as_ptr(),
                bytes.len(),
                &mut written,
            )
        })?;
        if written > bytes.len() {
            return Err(SdkError::invalid("Invalid Host write length"));
        }
        Ok(written)
    }

    fn chunk_create(&self, bytes: &[u8]) -> Result<ChunkRef> {
        let mut output = [0u8; 128];
        let mut length = 0;
        check_status(unsafe {
            (self.0.chunk_create)(
                self.0.user_data,
                bytes.as_ptr(),
                bytes.len(),
                output.as_mut_ptr(),
                output.len(),
                &mut length,
            )
        })?;
        Ok(ChunkRef(
            std::str::from_utf8(
                output
                    .get(..length)
                    .ok_or_else(|| SdkError::invalid("Invalid chunk id length"))?,
            )
            .map_err(SdkError::parse)?
            .to_owned(),
        ))
    }

    fn chunk_copy(&self, id: &ChunkRef) -> Result<Vec<u8>> {
        let mut output = vec![0u8; MAX_MEDIA_CHUNK_BYTES as usize];
        let mut length = 0;
        check_status(unsafe {
            (self.0.chunk_copy)(
                self.0.user_data,
                id.0.as_ptr(),
                id.0.len(),
                output.as_mut_ptr(),
                output.len(),
                &mut length,
            )
        })?;
        if length > output.len() {
            return Err(SdkError::invalid("Invalid chunk length"));
        }
        output.truncate(length);
        Ok(output)
    }
}

pub const fn abi<P: Plugin>() -> NativePluginAbiV2 {
    NativePluginAbiV2 {
        header: NativeAbiHeader {
            abi_revision: NATIVE_ABI_REVISION,
            struct_size: std::mem::size_of::<NativePluginAbiV2>() as u32,
        },
        target: NativeTargetInfo::CURRENT,
        create: create::<P>,
        destroy: destroy::<P>,
        supports: supports::<P>,
        invoke: invoke::<P>,
    }
}

unsafe extern "C" fn create<P: Plugin>() -> *mut c_void {
    std::panic::catch_unwind(|| Box::into_raw(Box::new(P::default())).cast())
        .unwrap_or(std::ptr::null_mut())
}

unsafe extern "C" fn destroy<P: Plugin>(instance: *mut c_void) {
    if !instance.is_null() {
        let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            drop(unsafe { Box::from_raw(instance.cast::<P>()) });
        }));
    }
}

unsafe extern "C" fn supports<P: Plugin>(_: *mut c_void, pointer: *const u8, len: usize) -> bool {
    if pointer.is_null() || len > 128 {
        return false;
    }
    std::str::from_utf8(unsafe { std::slice::from_raw_parts(pointer, len) }).is_ok_and(|name| {
        matches!(name, "initialize" | "shutdown") || P::OPERATIONS.contains(&name)
    })
}

unsafe extern "C" fn invoke<P: Plugin>(
    instance: *mut c_void,
    operation: *const u8,
    operation_len: usize,
    input: *const u8,
    input_len: usize,
    host: *const NativeHostApiV2,
    allocator: NativeHostAllocator,
    output: *mut NativeCallOutput,
) -> i32 {
    if instance.is_null()
        || operation.is_null()
        || operation_len > 128
        || input.is_null()
        || input_len > MAX_CONTROL_BYTES
        || output.is_null()
        || host.is_null()
    {
        return NativeStatus::InvalidInput as i32;
    }
    let header = unsafe { &*host.cast::<NativeAbiHeader>() };
    if header.abi_revision != NATIVE_ABI_REVISION
        || header.struct_size as usize != std::mem::size_of::<NativeHostApiV2>()
    {
        return NativeStatus::InvalidInput as i32;
    }
    let host = unsafe { &*host };
    if host.target != NativeTargetInfo::CURRENT {
        return NativeStatus::InvalidInput as i32;
    }
    let operation =
        std::str::from_utf8(unsafe { std::slice::from_raw_parts(operation, operation_len) });
    let input = serde_json::from_slice(unsafe { std::slice::from_raw_parts(input, input_len) });
    let (Ok(operation), Ok(input)) = (operation, input) else {
        return NativeStatus::InvalidInput as i32;
    };
    let result = crate::dispatch(
        unsafe { &mut *instance.cast::<P>() },
        operation,
        input,
        &NativeHost(host),
    );
    let Ok(bytes) = serde_json::to_vec(&result) else {
        return NativeStatus::InternalError as i32;
    };
    if bytes.len() > MAX_CONTROL_BYTES {
        return NativeStatus::ResourceLimit as i32;
    }
    let buffer = unsafe { (allocator.allocate)(allocator.user_data, bytes.len()) };
    if buffer.is_null() {
        return NativeStatus::ResourceLimit as i32;
    }
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), buffer, bytes.len());
        *output = NativeCallOutput {
            data: buffer,
            len: bytes.len(),
        };
    }
    NativeStatus::Ok as i32
}
